# Site Settings
locale                   : "en"
title                    : "Vincent Sabourdy"
title_separator          : "-"
name                     : "Vincent Sabourdy"
description              : "An amazing blog."
url                      : "https://vsabourdy.github.io"
baseurl                  : "/" 
repository               : "vsabourdy/vsabourdy" 
words_per_minute         : 200
minimal_mistakes_skin    : "contrast"
comments:
  provider               : "disqus" 
  disqus:
    shortname            : "vsabourdy"


# Analytics
analytics:
  provider               : false 


# Site Author
author:
  name             : "Vincent SABOURDY"
  avatar           : 
  bio              : 
  location         : "Somewhere in France"
  email            : "vincent.sabourdy1@gmail.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  github           : "vsabourdy"
  linkedin         : "vincent-sabourdy-312655a5"
  stackoverflow    : "5108988/ivaprag"
  twitter          :
  youtube          : 


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
